branch-defaults:
  master:
    environment: KakaoBot-dev
    group_suffix: null
environment-defaults:
  KakaoBot-dev:
    branch: master
    repository: origin
global:
  application_name: KakaoBot
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
