branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  KakaoBot-dev:
    branch: null
    repository: null
global:
  application_name: kakao-env-dev
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: kakao-env
  sc: git
  workspace_type: Application
